### ISSUE TITLE
Live ISO fails to install

### ISSUE THREAD

**Issue by electricduck** [sodaliterocks/bootable#5] opened 2022-01-17 22:10 UTC
Built `sodalite/stable/x86_64/stable` from the `devel` branch and generated an ISO using the script from this repo. ISO boots fine into the installer, but it eventually crashes during install. As seen in the below trace it stumbles on a missing file (`/mnt/sysroot/etc/resolv.conf`).

```
anaconda 35.22.2 exception report
Traceback (most recent call first):
  File "/usr/lib/python3.10/site-packages/dasbus/client/handler.py", line 497, in _handle_method_error
    raise exception from None
  File "/usr/lib/python3.10/site-packages/dasbus/client/handler.py", line 477, in _get_method_reply
    return self._handle_method_error(error)
  File "/usr/lib/python3.10/site-packages/dasbus/client/handler.py", line 444, in _call_method
    return self._get_method_reply(
  File "/usr/lib64/python3.10/site-packages/pyanaconda/modules/common/task/__init__.py", line 46, in sync_run_task
    task_proxy.Finish()
  File "/usr/lib64/python3.10/site-packages/pyanaconda/network.py", line 293, in write_configuration
    sync_run_task(task_proxy)
  File "/usr/lib64/python3.10/site-packages/pyanaconda/installation_tasks.py", line 458, in run_task
    self._task(*self._task_args, **self._task_kwargs)
  File "/usr/lib64/python3.10/site-packages/pyanaconda/installation_tasks.py", line 496, in start
    self.run_task()
  File "/usr/lib64/python3.10/site-packages/pyanaconda/installation_tasks.py", line 311, in start
    item.start()
  File "/usr/lib64/python3.10/site-packages/pyanaconda/installation_tasks.py", line 311, in start
    item.start()
  File "/usr/lib64/python3.10/site-packages/pyanaconda/installation_tasks.py", line 311, in start
    item.start()
  File "/usr/lib64/python3.10/site-packages/pyanaconda/installation.py", line 415, in run_installation
    queue.start()
  File "/usr/lib64/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.10/site-packages/pyanaconda/threading.py", line 275, in run
    threading.Thread.run(self)
dasbus.error.DBusError: [Errno 2] No such file or directory: '/mnt/sysroot/etc/resolv.conf'
```

This seems to be related to https://bugzilla.redhat.com/show_bug.cgi?id=2019579. Although this issue was opened in late November 2021 so I'm surprised this has only just occurred now.

Full output: [anaconda.log](https://github.com/sodaliterocks/bootable/files/7884889/anaconda.log).

**Comment by ACertainTopfi** [comment] 2022-01-19 23:33
Was able to reproduce this and have verified that it was not present on older images. Fix is being pushed with newer versions of Anaconda.

Either, we temporarily adjust the script to use a newer Anaconda release or we rely on Fedora 34 for testing. Rawhide should also work in this case.

**Comment by electricduck** [comment] 2022-01-20 19:31
I'm good with changing to the newer version of Anaconda if its not too much work.

**Comment by ACertainTopfi** [comment] 2022-01-22 06:20
For the time being, I have addressed this by changing the script to building Rawhide releases: https://github.com/sodaliterocks/bootable/commit/55867baccc9a5771b5e023268c5cc2ad8e39eed1

That seemed to be the cleanest way of getting around this issue at this time. I will look into creating a workaround for Fedora 35 as soon as possible, though as we have both a devel and main branch, perhaps keeping a Rawhide build script around makes sense in the long term.

**Comment by electricduck** [comment] 2022-01-22 14:12
So, would this still install as Fedora 35, and its just the live ISO that's running as rawhide? Because if that's the case I don't see any problem in it being like this.

**Comment by ACertainTopfi** [comment] 2022-01-22 18:10
No, sadly the image build in this case results in a Rawhide install. That's why I'm still working on getting the newest version of Anaconda working with 35.

**Comment by electricduck** [comment] 2022-01-23 20:46
No, what I mean is the actual installed OS is still Fedora 35. Having just tried a build myself, it seems it is, and its just the live OS that's Rawhide.

**Comment by ACertainTopfi** [comment] 2022-01-23 21:12
Yes, you are correct, the installed OS is based on Fedora 35. I will be honest, I simply misunderstood the question and my answer wasn't worded all to well either...
Since this does work and produces a proper 35 installation, I will close this, though I am still intending on changing over to regular (non Rawhide) Fedora for the Anaconda environment, once that is possible.

**Closed by ACertainTopfi** 2022-01-23 21:12 UTC
Labels: 🐞 issue

**Comment by electricduck** [comment] 2022-01-24 04:08
> Since this does work and produces a proper 35 installation, I will close this, though I am still intending on changing over to regular (non Rawhide) Fedora for the Anaconda environment, once that is possible.

Oh, of course. Is a little jarring it says "Sodalite Rawhide" currently, but at least it works now :+1:.
